-- ============================================================
-- CRÉER TON COMPTE ADMIN — Maison Sol Noble CRM
-- Colle ce SQL dans Supabase > SQL Editor > New Query
--
-- ⚠️ NE JAMAIS écrire de vrai mot de passe dans ce fichier.
-- Ce dépôt est public sur GitHub : tout ce qui est écrit ici
-- est visible par n'importe qui sur internet.
--
-- Pour créer ou modifier ton compte CRM en toute sécurité,
-- utilise l'interface Supabase directement :
-- Authentication > Users > Add user / Reset password
-- (ne passe jamais par ce script pour définir un vrai mot de passe)
-- ============================================================

-- Exemple de structure si tu veux créer un compte par script
-- (remplace <EMAIL> et utilise le champ "Reset password" de
-- l'interface Supabase pour le mot de passe, jamais ici) :

-- SELECT supabase_admin.create_user(
--   '{"email": "<EMAIL>", "email_confirm": true}'::jsonb
-- );
-- Puis va dans Authentication > Users > [ton compte] > Reset password
-- pour définir le mot de passe directement dans l'interface Supabase.
